{% set name = "thredds_crawler" %}
{% set version = "1.4.0" %}
{% set md5 = "74984e6e77314fd6b466c5e6f853c9fe" %}
{% set build = 0 %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://pypi.python.org/packages/ef/72/cd479deb55378e96ce3a354e7815e66fa630ead3dd1daa272b7dea0f736f/thredds_crawler-1.4.0.tar.gz
    md5: {{ md5 }}

build:
    number: {{ build }}
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - requests
        - lxml
        - netcdf4
        - pytz

test:
    imports:
        - tests
        - thredds_crawler

about:
    home: https://github.com/asascience-open/thredds_crawler
    license: GPL-3.0
    summary: A Python library for crawling THREDDS servers

extra:
    recipe-maintainers:
        - kwilcox
        - ocefpaf
